### ISSUE TITLE
constructing a mask for the first N lanes

### ISSUE THREAD

**Issue by ibaned** [mattkretz/std-simd-feedback#23]
With the latest version of the proposal, is there a canonical way to construct a `simd_mask<T, Abi>` that is `true` for the first N lanes and false otherwise?

**Comment by bernhardmgruber** [comment]
For a moment I thought: Just use the constructor with the generator functor which is called with integral constants. But then I checked the parallelism TS and it seems that constructor is only present on `simd<T, Abi>` and not on `simd_mask<T, Abi>`. So +1 for adding such a constructor!

**Comment by ibaned** [comment]
Agreed! generator constructor on the `simd_mask` class template would be great

**Comment by mattkretz** [comment]
Yes, I already have the missing `simd_mask` generator ctor in P1928, which calls for the merge to the IS. In the meantime, since I needed the ctor myself, I added one to libstdc++ a long time ago. But it's hidden behind a name that nobody is allowed to utter :wink:
```c++
stdx::native_simd_mask<int>(stdx::__private_init, [](auto i) { return i < 3; });
```
https://godbolt.org/z/aW1erdn6s

Feel free to use it, but don't complain if it's not portable or stops working even with libstdc++.
