### ISSUE TITLE
What do both any_of and some_of do?

### ISSUE THREAD

**Issue by DenisYaroshevskiy** [mattkretz/std-simd-feedback#66]
28.9.9.4  mentions both any_of and some_of.
My understanding would be that these are the same thing.
if not - can we have more obvious names

**Comment by mattkretz** [comment]
`some_of` has already been removed for the C++26 merge (because nobody understood/used it). Have you been looking at R3 or R4 of P1928?
`some_of` is the condition "I have more work to do, but at least one lane is idle", IOW `any_of and not all_of`. This can make a difference in code-gen: https://compiler-explorer.com/z/9jEK4dWMT. But again, dropped for C++26.
