### ISSUE TITLE
Pushing back against expression templates (where).

### ISSUE THREAD

**Issue by DenisYaroshevskiy** [mattkretz/std-simd-feedback#68]
Hi

I appreciate that in Vc library you need expression templates to generate conditional operations.
However, if this is in the standard, putting effort to produce masked operations in the optimizer seems to be much cheaper then doing expression templates.

My big concern that this is much harder to use then, let's say, eager `if_else(cond, true_case, false_case) -> simd_value`.

Writing templates against these will be much harder.

What's the motivation for where?

**Comment by mattkretz** [comment]
The Vc library actually had a "concept" of a *masked vector*. Basically a `simd` which implicitly applies a mask to all its operations.

WG21/SG1 wanted to have less magic and we settled on `where(mask, lvalue) op rhs`, where `op` can be assignment or compound assignment. This expresses masked *operations* much better than an `if_else(...)` which only blends results. At this point we can leave the contraction of blending results and operations up to compilers. Back when I designed Vc that wasn't the case (note that I incorporated AVX-512-like instructions from the start in 2009 because I was designing for Larrabee GPUs).

In any case, P1928R4 removed all of `where` and `where_expression`. So I believe this issue is resolved?

**Comment by DenisYaroshevskiy** [comment]
> In any case, P1928R4 removed all of where and where_expression. So I believe this issue is resolved?

Oh - did I not look at the latest version of the paper??

I was looking through this: https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2023/p1928r2.pdf

**Comment by DenisYaroshevskiy** [comment]
Closing yes, no expression templates is much better
