### ISSUE TITLE
no default for the load/store flags

### ISSUE THREAD

**Issue by mattkretz** [mattkretz/std-simd-feedback#8]
Consider:
```cpp
std::simd<float> v(addr, std::vector_aligned);
v.copy_from(addr + 1, std::element_aligned);
v.copy_to(dest, std::element_aligned);
```
Line 1 supplies an optimization hint to the load operation. Line 2 says what really?
“Please don’t crash. I know this is not a vector aligned access2 .” Line 3 says: “I don’t
know whether it’s vector aligned or not. Compiler, if you know more, please optimize,
otherwise just don’t make it crash.” (To clarify, the difference between lines 2 and 3
is what line 1 says about the alignment of `addr`.) In both cases of `element_aligned`
access, the developer requested a behavior we take as given in all other situations.
Why do we force to spell it out in this case?
Since C++20, we also have another option:
```cpp
std::simd<float> v(std::assume_aligned<std::memory_alignment_v<std::simd<float>>>(addr));
v.copy_from(addr + 1);
v.copy_to(dest);
```
This seems to compose well, except that line 1 is rather long for a common pattern in
this interface. Also, this removes implementation freedom because the library cannot
statically determine the alignment properties of the pointer.
Consequently, I suggest to keep the load/store flags as in the TS but default them
to `element_aligned`. I.e.:
```cpp
std::simd<float> v(addr, std::vector_aligned);
v.copy_from(addr + 1);
v.copy_to(dest);
```

**Comment by bernhardmgruber** [comment]
I just started to try `std::experimental::simd` with GCC11 and also encountered this annoyance. Sprinkling the corresponding flags for loading and storing SIMD types from and to memory occurs in a lot of places and impeds readability of the code more than it adds value.

In most cases I just want to load/store from a `T*` and it is fine if the compiler emits an unaligned load instruction (= `std::element_aligned`), because in case the address behind the `T*` is aligned at runtime, my CPU performs well anyway.
Furthermore, if the compiler can inline the load into the same scope as the memory allocation, which happens to be aligned, the compiler can already generate an aligned load instruction (observed with Vc on g++10).

Thus, having `std::element_aligned` as default may still result in the compiler generating an aligned load or the hardware perform an aligned load.

**Comment by mattkretz** [comment]
up to WG21 now
